---
- name: compute file content validation tests
  hosts: compute
  become: true
  vars:
    osd_memory_target: "{{ [(1048576*ansible_memtotal_mb*0.2 / ((test.osds.number | int) / (test.pool.size | int))) | round(0, 'floor') | int, 4294967296] | max }}"
  tasks:
    - name: validate the default values of max_files & max_processes parameters in /etc/libvirt/qemu.conf (BZ#1372589)
      include: tasks/check_qemu_values.yml
      tags:
        - compute
        - file_contents

    - name: validate ceph keyring permissions (BZ#1734513)
      include: tasks/check_keyring_permissions.yml
      tags:
        - compute
        - file_contents
        - containerized

    # - name: write calculation vars to console
    #   debug:
    #     msg:
    #       - ansible_memtotal_mb: "{{ ansible_memtotal_mb }}"
    #       - osds_number: "{{ test.osds.number }}"
    #       - pool_size: "{{ test.pool.size }}"
    #       - osd_memory_target: "{{ osd_memory_target }}"

    - name: validate osd memory target in /etc/ceph/ceph.conf (BZ#1664112)
      include: tasks/check_mem_target.yml
      tags:
        - compute
        - file_contents
        - containerized
        - HCI

- name: undercloud file content validation tests
  hosts: undercloud
  become: true
  tasks:
    - name: validate ceph dashboard container images in /usr/share/openstack-tripleo-common/container-images/overcloud_containers.yaml (BZ#1785692)
      include: tasks/check_dashboard_containers.yml
      tags:
        - undercloud
        - file_contents
        - containerized
        - dashboard
