---
- name: ceph monitor validation tests
  hosts: "{{ test.monitor.nodes }}"
  tasks:
    - name: validate monitors health status for ceph2.x
      include: tasks/check_monitors_health_ceph.yml
      with_items: "{{ (cluster_status.stdout|from_json).health.timechecks.mons }}"
      run_once: yes
      tags:
        - monitors
        - sanity
        - ceph-2
    - name: validate monitors health status for ceph3.x
      include: tasks/check_monitors_health_ceph.yml
      with_items: "{{ (cluster_status.stdout|from_json).health.status }}"
      run_once: yes
      tags:
        - monitors
        - sanity
        - ceph-3
    - name: validate monitors health status for ceph4.x
      include: tasks/check_monitors_health_ceph.yml
      with_items: "{{ (cluster_status.stdout|from_json).health.status }}"
      run_once: yes
      tags:
        - monitors
        - sanity
        - ceph-4