---
- name: validate ceph osds status
  hosts: "{{ test.monitor.nodes }}"
  tasks:
    - name: check OSDs were created
      fail:
        msg: "number of OSDs is {{ (cluster_status.stdout|from_json).osdmap.osdmap.num_osds }}"
      when: (cluster_status.stdout|from_json).osdmap.osdmap.num_osds != {{ test.osds.number }}
      run_once: yes
      tags:
        - osds
        - sanity

    - name: get osds list
      shell: "ceph osd tree --format json"
      become: true
      register: osds_list
      run_once: yes
      tags:
        - osds
        - sanity
        - non-containerized

    - name: get osds list
      shell: "{{test.ceph.reg.provider}} exec ceph-mon-`hostname -s` ceph osd tree --format json"
      become: true
      register: osds_list
      run_once: yes
      tags:
        - osds
        - sanity
        - containerized
        - ceph-3
    - name: get osds list
      shell: "{{test.ceph.reg.provider}} exec ceph-mon-`hostname -s` ceph osd tree --format json"
      become: true
      register: osds_list
      run_once: yes
      tags:
        - osds
        - sanity
        - containerized
        - ceph-4
    - name: check osds status
      include: tasks/check_osds_status.yml
      with_items: '{{ (osds_list.stdout|from_json).nodes }}'
      run_once: yes
      tags:
        - osds
        - sanity