---
- name: get pool's size
  shell: "ceph osd pool get {{ item }} size --format json"
  become: true
  run_once: yes
  register: size
  tags:
    - non-containerized

- name: get pool's size
  shell: "{{test.ceph.reg.provider}} exec ceph-mon-`hostname -s` ceph osd pool get {{ item }} size --format json"
  become: true
  run_once: yes
  register: size
  tags:
    - containerized

- name: is size equal to value
  fail:
    msg: "the size of {{ item }} is not equal to {{ test.pool.size }}"
  when: (size.stdout|from_json).size != {{ test.pool.size }}
  run_once: yes

- name: get pool's min_size
  shell: "ceph osd pool get {{ item }} min_size --format json"
  become: true
  run_once: yes
  register: min_size
  tags:
    - non-containerized

- name: get pool's min_size
  shell: "{{test.ceph.reg.provider}} exec ceph-mon-`hostname -s` ceph osd pool get {{ item }} min_size --format json"
  become: true
  run_once: yes
  register: min_size
  tags:
    - containerized

- name: is min_size equal to value
  fail:
    msg: "the min_size of {{ item }} is not equal to {{ test.pool.min_size }}"
  when: (min_size.stdout|from_json).min_size != {{ test.pool.min_size }}
  run_once: yes