---
- name: get pool's pg_num
  shell: "ceph osd pool get {{ item }} pg_num --format json"
  become: true
  run_once: yes
  register: pg_num
  tags:
    - non-containerized

- name: get pool's pg_num
  shell: "{{test.ceph.reg.provider}} exec ceph-mon-`hostname -s` ceph osd pool get {{ item }} pg_num --format json"
  become: true
  run_once: yes
  register: pg_num
  tags:
    - containerized

- name: is pg_num equal to value
  fail:
    msg: "the pg_num of {{ item }} is not equal to {{ test.pool.pg_num }}"
  when: (pg_num.stdout|from_json).pg_num != {{ test.pool.pg_num }}
  run_once: yes

- name: get pool's pgp_num
  shell: "ceph osd pool get {{ item }} pgp_num --format json"
  become: true
  run_once: yes
  register: pgp_num
  tags:
    - non-containerized

- name: get pool's pg_num
  shell: "{{test.ceph.reg.provider}} exec ceph-mon-`hostname -s` ceph osd pool get {{ item }} pgp_num --format json"
  become: true
  run_once: yes
  register: pgp_num
  tags:
    - containerized


- name: is pgp_num equal to value
  fail:
    msg: "the pgp_num of {{ item }} is not equal to {{ test.pool.pgp_num }}"
  when: (pgp_num.stdout|from_json).pgp_num != {{ test.pool.pgp_num }}
  run_once: yes